name: ${project.artifactId}
description: ${project.description}
main: ${project.mainclass}
version: ${project.version}
author: Black_ixx
website: http://felix.neuby.de
softdepend: [Votifier, SQLibrary, Vault]
commands:
  points:
   description: Root command for PlayerPoints
   usage: /points <param>
  p:
   description: the same as /points
   usage: /p <param>
permissions:
    PlayerPoints.*:
        description: Gives access to all PlayerPoints commands
        children:
            PlayerPoints.give: true
            PlayerPoints.giveall: true
            PlayerPoints.take: true
            PlayerPoints.look: true
            PlayerPoints.pay: true
            PlayerPoints.set: true
            PlayerPoints.reset: true
            PlayerPoints.lead: true
            PlayerPoints.reload: true
    PlayerPoints.give:
        description: Gives access to the give command
        default: op
    PlayerPoints.giveall:
        description: Gives access to the giveall command
        default: op
    PlayerPoints.take:
        description: Gives access to the take command
        default: op
    PlayerPoints.look:
        description: Gives access to the look command
        default: op
    PlayerPoints.pay:
        description: Gives access to the pay command
        default: op
    PlayerPoints.broadcast:
        description: Give access to the broadcast command
        default: op
    PlayerPoints.set:
        description: Gives access to the set command
        default: op
    PlayerPoints.reset:
        description: Gives access to the reset command
        default: op
    PlayerPoints.lead:
        description: Gives access to the lead command
        default: op
    PlayerPoints.reload:
        description: Gives access to the reload command
        default: op